project:
  name: quickstart-amazon-aurora-mysql
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
tests:
  aurora-mysql:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      DBEngineVersion: Aurora-MySQL5.7.12
      DBMasterUserPassword: $[taskcat_genpass_8S]
      DBMultiAZ: "false"
      EnableBastion: "false"
      KeyPairName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RemoteAccessCIDR: 10.0.0.0/16
    template: ./templates/aurora_mysql-master.template.yaml
